### ISSUE TITLE
Hi, I don't understand step 3.

### ISSUE THREAD

**Issue by bemoregt** [bakercp/ofxTSNEParallel#2]
Hi, @bakercp 

I don't understand step 3 in MacOSX.

In my Mojave terminal, What is the correct command for step-3?  
Step 1~2, I've already done.

Thanks in advance ~.

**Comment by bakercp** [comment]
Step 4, 5, 6 are how you do step 3.

**Comment by bakercp** [comment]
Clarified with 0d7d3b9
